project:
  type: website
  output-dir: docs

website:
  title: "RISEBA Prognozēšanas metodes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - LRKPM.qmd
      - regr.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



